"""add users and task user relationship

Revision ID: b01b548e02df
Revises: c59a083b891f
Create Date: 2026-09-24 21:03:14.208412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01b548e02df'
down_revision: Union[str, Sequence[str], None] = 'c59a083b891f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute(
        "INSERT INTO users (name, email) VALUES ('Default User', 'default@example.com')"
    )

    op.execute(
        "UPDATE tasks SET user_id = (SELECT id FROM users WHERE email = 'default@example.com')"
    )
    op.create_foreign_key("fk_tasks_user_id_users", 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

    op.alter_column(
    'tasks',
    'user_id',
    existing_type=sa.Integer(),
    nullable=False
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_tasks_user_id_users", 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
